services:
  - type: web
    name: project-foresight-dashboard
    runtime: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run src/dashboard.py --server.address 0.0.0.0 --server.port $PORT
    autoDeploy: true
